# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Remote-medical-System' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Remote-medical-System
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SnapKit'
pod 'SVProgressHUD'

end
