# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Remote_medical_System_patient’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Remote_medical_System_patient
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SnapKit'
pod 'SVProgressHUD'

end
